const PatientLabels = {
  //* General Fields -----------------------------------------------------------
  fields: {
    mrn: 'MRN',
    name: 'Name',
    birthdate: 'Date of Birth',
    gender: 'Gender',
    maritalStatus: 'Marital Status',
    idType: 'ID Type',
    idNumber: 'NRIC / FIN / Passport Number',
    contactNumber: 'Contact Number',
    email: 'Email',
    active: 'Active',
    contact: {
      relationship: 'Contact Relationship',
      name: 'Contact Name',
      telecom: 'Contact Number',
    },
  },

  //* Dropdown Options ---------------------------------------------------------
  options: {
    gender: {
      male: 'Male',
      female: 'Female',
      unknown: 'Unknown',
    },
    maritalStatus: {
      single: 'Single',
      married: 'Married',
      divorced: 'Divorced',
      widowed: 'Widowed',
    },
    idType: {
      citizen: 'Singapore Citizen (NRIC)',
      pr: 'Singapore Permanent Resident (NRIC)',
      passholder: 'Long-Term Pass Holder (FIN)',
      foreigner: 'Foreigner (Passport)',
    },
    relationship: {
      PRN: 'Parent',
      CHILD: 'Child',
      SPS: 'Spouse',
      SIB: 'Sibling',
      DOMPART: 'Domestic Partner',
      GPARNT: 'Grandparent',
      GCHILD: 'Grandchild',
      NCHILD: 'Natural Child',
      STPCHILD: 'Stepchild',
      STPSIB: 'Stepsibling',
      ADOPT: 'Adopted Child',
      FTH: 'Father',
      MTH: 'Mother',
      SON: 'Son',
      DAU: 'Daughter',
      HUSB: 'Husband',
      WIFE: 'Wife',
      UNCLE: 'Uncle',
      AUNT: 'Aunt',
      NEPHEW: 'Nephew',
      NIECE: 'Niece',
      COUSN: 'Cousin',
      FRND: 'Friend',
      ROOM: 'Roommate',
      EMPL: 'Employer',
      EEC: 'Emergency Contact',
      GUARD: 'Guardian',
      POWATT: 'Power of Attorney',
      AGNT: 'Agent',
      CASEMGR: 'Case Manager',
      ADV: 'Advisor',
      CAREGIVER: 'Caregiver',
      PAYOR: 'Payor',
      PRES: 'Primary Care Provider',
      RELPRN: 'Related Person',
      EMC: 'Emergency Contact',
      OTH: 'Other',
      SIGOTHR: 'Significant Other',
    },
  },
};

export default PatientLabels;
